name: End-to-end tests
on: 
  deployment_status:
    environments:
      - pr-*

jobs:
    prepare-preview:
        # This job checks the deployment status and only passes if the deployment is successful
        # Only trigger for correct environment and status
        runs-on: ubuntu-latest
        # if: needs.files-changed.outputs.frontend == 'true' || needs.files-changed.outputs.backend == 'true'  || needs.files-changed.outputs.timezone == 'true'
        # needs: files-changed
        outputs:
            url: ${{ github.event.deployment_status.environment_url }}
        steps:
            - name: Check Okteto deployment status
              if: ${{ !(github.event.deployment_status.state == 'success' && github.event.deployment_status.environment_url != null) }}
              run: |
                  echo "Okteto environment ${{ github.event.deployment.environment }} is not ready: ${{ github.event.deployment_status.state }} ${{ github.event.deployment_status.environment_url }}"
                  exit 1